-- 学生信息表
CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    politics VARCHAR(255),
    code VARCHAR(255),
    gender VARCHAR(255),
    campusname VARCHAR(100),
    leavefailnum VARCHAR(255),
    classname VARCHAR(100),
    classid VARCHAR(50),
    identity VARCHAR(50),
    collegeid VARCHAR(50),
    id VARCHAR(50),
    credit VARCHAR(255),
    gradename VARCHAR(100),
    ethnic VARCHAR(255),
    majorid VARCHAR(50),
    userclasspass VARCHAR(255),
    sumscore DECIMAL(10,2),
    campusid VARCHAR(50),
    mobile VARCHAR(255),
    leavetotalnum VARCHAR(255),
    ethnicid VARCHAR(50),
    leavesuccessnum VARCHAR(255),
    collegename VARCHAR(100),
    grade VARCHAR(255),
    name VARCHAR(100),
    majorname VARCHAR(100),
    lengthname VARCHAR(100),
    status TINYINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
